### ISSUE TITLE
Construct models

### ISSUE THREAD

**Issue by wasade** [greengenes/Greengenes#20]
The following models are potentially minimal but not assured to be. Draft schema included in the issue. 
- [ ] `record`, `xref_source`, `publication`, `record_to_publication` (#12)
- [ ] `sequence`, `sequence_collection` (#13)
- [ ] `method` (#14)
- [ ] `detail_type`, `sequence_detail_numerical` and `sequence_detail_other` (#16)
- [ ] `locus`, `locus_type` (#15)
- [ ] `msa`, `multimsa`, `msa_mask` (#17)
- [ ] `phylogeny`, `msa_to_phylogeny`(#18)
- [ ] `taxonomy`, `taxonomy_type`, `taxonomy_to_sequence` (#19)
- [ ] `otu_cluster`, `otu_type` (#21)
- [ ] `release`, `release_sequences` (#22)
- [ ]  detail tables for other artifacts (e.g., phylogeny, taxonomy, etc) (#23)

![ggdraft](https://cloud.githubusercontent.com/assets/474290/12040747/693d17be-ae20-11e5-92e3-0f64f973639a.png)
